#!/bin/bash


###### Set some default variables ######
TITLE="Vbox Shell Control"
LOG="/dev/tty7"
LIB_USER=~/projects/sh-vbox-control/usr/lib/vboxsh
LIB_CORE=$LIB_USER #Deprecated
TMPDIR=/tmp/vboxsh
LOGDIR=/var/log/vboxsh
LOGFILE=$LOGDIR/vboxsh.log
DISCLAIMER="Note that despite our not-so-careful coding and proper testing there may still be bugs in this software."
UI="dia"
DIACMD="cdialog"


export LC_COLLATE=C # for consistent sorting behavior

###### DEBUGGING #######

LOG_TO_FILE=0

# $1 library name   
load_lib ()
{
	[ -z "$1" ] && die_error "load_library needs a library as \$1"
	log "Loading library /libs/$1 ..."
	lib=$LIB_USER/"$1"
	
	source $lib || die_error "Something went wrong while sourcing library $lib"
}

###### Bootstrapping ######
# source and assign default User Interface for libui.sh
source $LIB_USER/libui.sh
libui_sh_init $UI

load_lib lib-flowcontrol.sh
load_lib lib-interactive.sh
load_lib lib-misc.sh
load_lib lib-vboxmanage.sh

###### perform actual logic ######
echo "Welcome to $TITLE"


# Processes args that were not already matched by the basic rules.
process_args ()
{
	# known options: we don't know any yet
	# return 0

	# if we are still here, we didn't return 0 for a known option. hence this is an unknown option
	usage
	exit 5
}

while getopts ":i:dlp:$var_OPTS_STRING" OPTION
do
	case $OPTION in
	i)
		[ -z "$OPTARG" ] && usage && exit 1 #TODO: check if it's necessary to do this. the ':' in $var_OPTS_STRING might be enough
		[ "$OPTARG" != cli -a "$OPTARG" = !dia ] && die_error "-i must be dia or cli"
		libui_sh_init $OPTARG
		;;
	d)
		export DEBUG=1
		LOG_TO_FILE=1
		;;
	l)
		LOG_TO_FILE=1
		;;
	h)
		usage
		exit
		;;
	?)
		# If we hit something elso, call process_args
		process_args -$OPTION $OPTARG # you can override this function in your profile to parse additional arguments and/or override the behavior above
		;;
	esac

done


start_interactive

exit_vboxsh
